[package]
name = "swayidle-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
futures = { version = "0.3.29", features = ["compat"] }
futures-channel = "0.3.29"
futures-util = { version = "0.3.29", features = ["futures-channel"] }
mlua = { version = "0.9.1", features = ["async", "luau", "send"] }
tokio = { version = "1.32.0", features = ["rt", "macros", "process", "rt-multi-thread"] }
wayland-client = "0.31.1"
wayland-protocols = { version = "0.31.0", features = ["client", "staging"] }
zbus = { version = "3.14.1", features = ["tokio"] }
